### ISSUE TITLE
Add: Option to share created plan as image

### ISSUE THREAD

**Issue by Rolf-Smit** [NeoTech-Software/Abysner#1]
Right now the only way to share a plan is to take a screenshot, it would be beneficial if users can just use a convenient share button instead.

**Comment by hansalves** [comment]
As image you can just use a screenshot, but it might be nice to be able to import/export dives as structured data (I,E. json) so you can share that and make changes after importing.

**Comment by Rolf-Smit** [comment]
This has been implemented in #18, so I'm closing this issue.

I created new issues for sharing plans as text: #22 and one for import and export as structured data: #21.
